# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 16:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('matricula', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Matr\xedcula')),
                ('nascimento', models.DateField(blank=True, null=True)),
                ('telefone', models.CharField(blank=True, default='(Nenhum)', help_text='4798877-6655', max_length=20, null=True, verbose_name='Telefone do aluno')),
                ('nome', models.CharField(help_text='Nome completo do aluno', max_length=100)),
                ('cidade', models.CharField(blank=True, max_length=60, null=True)),
                ('turma', models.CharField(blank=True, choices=[('1A', '1A'), ('1B', '1B'), ('1C', '1C'), ('1E', '1E'), ('2A', '2A'), ('2B', '2B'), ('2C', '2C'), ('2E', '2E'), ('3A', '3A'), ('3B', '3B'), ('3C', '3C'), ('3E', '3E'), ('SubAI', 'SubAI'), ('SubAII', 'SubAII')], max_length=8, null=True)),
                ('alojamento', models.CharField(blank=True, choices=[('1A', '1A'), ('1B', '1B'), ('1C', '1C'), ('1D', '1D'), ('1E', '1E'), ('1F', '1F'), ('2A', '2A'), ('2B', '2B'), ('2C', '2C'), ('2D', '2D'), ('2E', '2E'), ('2F', '2F'), ('3A', '3A'), ('3B', '3B'), ('3C', '3C'), ('3D', '3D'), ('3E', '3E'), ('3F', '3F'), ('4A', '4A'), ('4B', '4B'), ('4C', '4C'), ('4D', '4D'), ('4E', '4E'), ('4F', '4F'), ('5A', '5A'), ('5B', '5B'), ('5C', '5C'), ('5D', '5D'), ('5E', '5E'), ('5F', '5F'), ('6A', '6A'), ('6B', '6B'), ('6C', '6C'), ('6D', '6D'), ('6E', '6E'), ('6F', '6F'), ('7A', '7A'), ('7B', '7B'), ('7C', '7C'), ('7D', '7D'), ('7E', '7E'), ('7F', '7F'), ('8A', '8A'), ('8B', '8B'), ('8C', '8C'), ('8D', '8D'), ('8E', '8E'), ('8F', '8F'), ('9A', '9A'), ('9B', '9B'), ('9C', '9C'), ('9D', '9D'), ('9E', '9E'), ('9F', '9F'), ('10A', '10A'), ('10B', '10B'), ('10C', '10C'), ('10D', '10D'), ('10E', '10E'), ('10F', '10F'), ('11A', '11A'), ('11B', '11B'), ('11C', '11C'), ('11D', '11D'), ('11E', '11E'), ('11F', '11F'), ('12A', '12A'), ('12B', '12B'), ('12C', '12C'), ('12D', '12D'), ('12E', '12E'), ('12F', '12F'), ('13A', '13A'), ('13B', '13B'), ('13C', '13C'), ('13D', '13D'), ('13E', '13E'), ('13F', '13F'), ('14A', '14A'), ('14B', '14B'), ('14C', '14C'), ('14D', '14D'), ('14E', '14E'), ('14F', '14F'), ('15A', '15A'), ('15B', '15B'), ('15C', '15C'), ('15D', '15D'), ('15E', '15E'), ('15F', '15F'), ('ZooI', 'ZooI'), ('ZooII', 'ZooII'), ('ZooIII', 'ZooIII')], max_length=5, null=True)),
                ('emancipado', models.BooleanField(default=False)),
                ('transferido', models.BooleanField(default=False)),
                ('abandonou', models.BooleanField(default=False)),
                ('faleceu', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['nome'],
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
            },
        ),
        migrations.CreateModel(
            name='Perfil_do_Servidor',
            fields=[
                ('matricula', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Matr\xedcula')),
                ('nascimento', models.DateField(blank=True, null=True)),
                ('telefone', models.CharField(blank=True, default='(Nenhum)', help_text='4798877-6655', max_length=20, null=True, verbose_name='Telefone do aluno')),
                ('carreira', models.CharField(choices=[('Docente', 'Docente'), ('T\xe9cnico Administrativo', 'T\xe9cnico Administrativo'), ('Tercerizado', 'Tercerizado')], default='T\xe9cnico Administrativo', max_length=50)),
                ('cargo', models.CharField(default='Assistente de alunos', max_length=100)),
                ('servidor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='servidor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil do servidor',
                'verbose_name_plural': 'Perfil dos servidores',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Pessoas.Aluno')),
                ('curso', models.CharField(choices=[('Agropecu\xe1ria', 'Agropecu\xe1ria'), ('Agroecologia', 'Agroecologia'), ('Inform\xe1tica', 'Inform\xe1tica'), ('Agrimensura', 'Agrimensura'), ('Eletroeletr\xf4nica', 'Eletroeletr\xf4nica'), ('Agronomia', 'Agronomia'), ('Ci\xeancia da Computa\xe7\xe3o', 'Ci\xeancia da Computa\xe7\xe3o'), ('Matem\xe1tica', 'Matem\xe1tica'), ('F\xedsica', 'F\xedsica'), ('Engenharia Mecatr\xf4nica', 'Engenharia Mecatr\xf4nica')], max_length=30)),
                ('forma', models.CharField(choices=[('T\xe9cnico Integrado', 'T\xe9cnico Integrado'), ('T\xe9cnico Subsequente', 'T\xe9cnico Subsequente'), ('Bacharelado', 'Bacharelado'), ('Engenharia', 'Engenharia'), ('Licenciatura', 'Licenciatura')], max_length=30)),
            ],
            options={
                'verbose_name': 'Curso do aluno',
                'verbose_name_plural': 'Curso de cada aluno',
            },
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Pessoas.Aluno')),
                ('pai', models.CharField(blank=True, max_length=80, null=True)),
                ('profissao_pai', models.CharField(blank=True, max_length=80, null=True, verbose_name='Profiss\xe3o do pai')),
                ('mae', models.CharField(blank=True, max_length=80, null=True, verbose_name='M\xe3e')),
                ('profissao_mae', models.CharField(blank=True, max_length=80, null=True, verbose_name='Profiss\xe3o da m\xe3e')),
                ('responsavel', models.CharField(blank=True, max_length=80, null=True, verbose_name='Respons\xe1vel')),
                ('telefone', models.CharField(default='(Nenhum)', help_text='4799878-6788', max_length=20, null=True, verbose_name='Telefone residencial')),
                ('telefone2', models.CharField(default='(Nenhum)', help_text='479999-9999', max_length=20, null=True)),
                ('telefone3', models.CharField(default='(Nenhum)', help_text='479999-9999', max_length=20, null=True)),
            ],
            options={
                'ordering': ['aluno'],
                'verbose_name': 'Fam\xedlia do aluno',
                'verbose_name_plural': 'Fam\xedlia de cada aluno',
            },
        ),
        migrations.CreateModel(
            name='Perfil_do_Aluno',
            fields=[
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='perfil_aluno', serialize=False, to='Pessoas.Aluno')),
                ('nota_ensino', models.FloatField(blank=True, default=7.0, max_length=4, null=True, verbose_name='Nota de ensino')),
                ('nota_comportamento', models.FloatField(blank=True, default=7.0, max_length=4, null=True, verbose_name='Nota de comportamento')),
                ('saude', models.CharField(blank=True, default=None, max_length=300, null=True, verbose_name='Sa\xfade')),
                ('reside', models.CharField(choices=[('Agr\xedcola', 'Agr\xedcola'), ('Urbano', 'Urbano')], max_length=10, verbose_name='Reside em local')),
                ('objetivos', models.CharField(blank=True, choices=[('Curso superior na \xe1rea agr\xedcola', 'Curso superior na \xe1rea agr\xedcola'), ('Curso superior fora da \xe1rea agr\xedcola', 'Curso superior fora da \xe1rea agr\xedcola'), ('Continuar trabalho familiar na agricultura', 'Continuar trabalho familiar na agricultura'), ('Trabalhar na \xe1rea do curso', 'Trabalhar na \xe1rea do curso'), ('N\xe3o sabe responder', 'N\xe3o sabe responder')], help_text='Objetivo ao completar o curso', max_length=300, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='Pessoas/')),
                ('motivo', models.CharField(blank=True, choices=[('Ensino M\xe9dio de qualidade', 'Ensino M\xe9dio de qualidade'), ('Curso t\xe9cnico', 'Curso t\xe9cnico'), ('Ambos', 'Ambos'), ('Outro', 'Outro')], help_text='Motivo pela escolha do IFC', max_length=100, null=True)),
            ],
            options={
                'ordering': ['aluno'],
                'verbose_name': 'Perfil do aluno',
                'verbose_name_plural': 'Perfil dos alunos',
            },
        ),
    ]
