# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dificuldade_por_disciplina',
            fields=[
                ('disciplina', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('numero_de_alunos', models.IntegerField(default=0, help_text='Quantidade de alunos com dificuldade nessa mat\xe9ria.')),
            ],
            options={
                'verbose_name': 'Aluno com dificuldade na disciplina',
                'verbose_name_plural': 'Alunos com dificuldade por disciplina',
            },
        ),
        migrations.CreateModel(
            name='Rendimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aprovados_sem_exame', models.IntegerField(default=0)),
                ('aprovados_com_exame', models.IntegerField(default=0)),
                ('reprovados', models.IntegerField(default=0)),
                ('com_dependencia', models.IntegerField(default=0)),
                ('ano', models.IntegerField(default=2016, help_text='Ano anterior ao vigente.')),
            ],
            options={
                'verbose_name': 'Rendimento escolar',
                'verbose_name_plural': 'Rendimentos escolares',
            },
        ),
    ]
