# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 16:25
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Pessoas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunicados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Aviso', 'Aviso'), ('Atendimento', 'Atendimento'), ('Alerta', 'Alerta'), ('Norma', 'Norma'), ('Sugest\xe3o', 'Sugest\xe3o'), ('Solicita\xe7\xe3o', 'Solicita\xe7\xe3o'), ('Elogio', 'Elogio'), ('Geral', 'Geral')], default='Geral', max_length=50)),
                ('texto', models.TextField(max_length=10000)),
                ('data', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Comunicado',
                'verbose_name_plural': 'Comunicados',
            },
        ),
        migrations.CreateModel(
            name='Educacional',
            fields=[
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Pessoas.Aluno')),
            ],
            options={
                'ordering': ['aluno__nome'],
                'verbose_name': 'Atendimento educacional',
                'verbose_name_plural': 'Atendimentos educacionais',
            },
        ),
        migrations.CreateModel(
            name='Educacional_detalhe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocorrencia', models.TextField(help_text='Descreva o atendimento', max_length=10000, verbose_name='Ocorr\xeancia')),
                ('setor', models.CharField(choices=[('CGAE', 'CGAE'), ('CGE', 'CGE'), ('CAE', 'CAE')], max_length=5)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('educacional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edu', to='Atividades.Educacional')),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Atendimento',
                'verbose_name_plural': 'Atendimentos',
            },
        ),
        migrations.CreateModel(
            name='Escala_Limpeza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana_inicio', models.DateField(verbose_name='Data do in\xedcio da semana')),
                ('semana_fim', models.DateField(verbose_name='Data do final da semana')),
                ('lixo', models.CharField(help_text='Alunos respons\xe1veis para recolher os lixos durante a semana', max_length=100)),
                ('limpeza', models.CharField(help_text='Alunos respons\xe1veis pela limpeza geral durante a semana', max_length=100)),
                ('quarto', models.CharField(choices=[('1A', '1A'), ('1B', '1B'), ('1C', '1C'), ('1D', '1D'), ('1E', '1E'), ('1F', '1F'), ('2A', '2A'), ('2B', '2B'), ('2C', '2C'), ('2D', '2D'), ('2E', '2E'), ('2F', '2F'), ('3A', '3A'), ('3B', '3B'), ('3C', '3C'), ('3D', '3D'), ('3E', '3E'), ('3F', '3F'), ('4A', '4A'), ('4B', '4B'), ('4C', '4C'), ('4D', '4D'), ('4E', '4E'), ('4F', '4F'), ('5A', '5A'), ('5B', '5B'), ('5C', '5C'), ('5D', '5D'), ('5E', '5E'), ('5F', '5F'), ('6A', '6A'), ('6B', '6B'), ('6C', '6C'), ('6D', '6D'), ('6E', '6E'), ('6F', '6F'), ('7A', '7A'), ('7B', '7B'), ('7C', '7C'), ('7D', '7D'), ('7E', '7E'), ('7F', '7F'), ('8A', '8A'), ('8B', '8B'), ('8C', '8C'), ('8D', '8D'), ('8E', '8E'), ('8F', '8F'), ('9A', '9A'), ('9B', '9B'), ('9C', '9C'), ('9D', '9D'), ('9E', '9E'), ('9F', '9F'), ('10A', '10A'), ('10B', '10B'), ('10C', '10C'), ('10D', '10D'), ('10E', '10E'), ('10F', '10F'), ('11A', '11A'), ('11B', '11B'), ('11C', '11C'), ('11D', '11D'), ('11E', '11E'), ('11F', '11F'), ('12A', '12A'), ('12B', '12B'), ('12C', '12C'), ('12D', '12D'), ('12E', '12E'), ('12F', '12F'), ('13A', '13A'), ('13B', '13B'), ('13C', '13C'), ('13D', '13D'), ('13E', '13E'), ('13F', '13F'), ('14A', '14A'), ('14B', '14B'), ('14C', '14C'), ('14D', '14D'), ('14E', '14E'), ('14F', '14F'), ('15A', '15A'), ('15B', '15B'), ('15C', '15C'), ('15D', '15D'), ('15E', '15E'), ('15F', '15F')], max_length=20)),
                ('nota', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'ordering': ['semana_inicio'],
                'verbose_name': 'Escala de limpeza',
                'verbose_name_plural': 'Escalas de limpeza',
            },
        ),
        migrations.CreateModel(
            name='Escala_Servidores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_da_semana', models.CharField(choices=[('Segunda-feira', 'Segunda-feira'), ('Ter\xe7a-feira', 'Ter\xe7a-feira'), ('Quarta-feira', 'Quarta-feira'), ('Quinta-feira', 'Quinta-feira'), ('Sexta-feira', 'Sexta-feira')], max_length=20)),
                ('horario_de_inicio', models.TimeField(verbose_name='Hor\xe1rio de in\xedcio')),
                ('intervalo_inicio', models.TimeField(blank=True, null=True, verbose_name='Hor\xe1rio inicial do intervalo')),
                ('intervalo_fim', models.TimeField(blank=True, null=True, verbose_name='Hor\xe1rio final do intervalo')),
                ('horario_de_saida', models.TimeField(verbose_name='Hor\xe1rio de sa\xedda')),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hor\xe1rio do servidor',
                'verbose_name_plural': 'Hor\xe1rio dos servidores',
            },
        ),
        migrations.CreateModel(
            name='Limpeza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarto', models.CharField(choices=[('1A', '1A'), ('1B', '1B'), ('1C', '1C'), ('1D', '1D'), ('1E', '1E'), ('1F', '1F'), ('2A', '2A'), ('2B', '2B'), ('2C', '2C'), ('2D', '2D'), ('2E', '2E'), ('2F', '2F'), ('3A', '3A'), ('3B', '3B'), ('3C', '3C'), ('3D', '3D'), ('3E', '3E'), ('3F', '3F'), ('4A', '4A'), ('4B', '4B'), ('4C', '4C'), ('4D', '4D'), ('4E', '4E'), ('4F', '4F'), ('5A', '5A'), ('5B', '5B'), ('5C', '5C'), ('5D', '5D'), ('5E', '5E'), ('5F', '5F'), ('6A', '6A'), ('6B', '6B'), ('6C', '6C'), ('6D', '6D'), ('6E', '6E'), ('6F', '6F'), ('7A', '7A'), ('7B', '7B'), ('7C', '7C'), ('7D', '7D'), ('7E', '7E'), ('7F', '7F'), ('8A', '8A'), ('8B', '8B'), ('8C', '8C'), ('8D', '8D'), ('8E', '8E'), ('8F', '8F'), ('9A', '9A'), ('9B', '9B'), ('9C', '9C'), ('9D', '9D'), ('9E', '9E'), ('9F', '9F'), ('10A', '10A'), ('10B', '10B'), ('10C', '10C'), ('10D', '10D'), ('10E', '10E'), ('10F', '10F'), ('11A', '11A'), ('11B', '11B'), ('11C', '11C'), ('11D', '11D'), ('11E', '11E'), ('11F', '11F'), ('12A', '12A'), ('12B', '12B'), ('12C', '12C'), ('12D', '12D'), ('12E', '12E'), ('12F', '12F'), ('13A', '13A'), ('13B', '13B'), ('13C', '13C'), ('13D', '13D'), ('13E', '13E'), ('13F', '13F'), ('14A', '14A'), ('14B', '14B'), ('14C', '14C'), ('14D', '14D'), ('14E', '14E'), ('14F', '14F'), ('15A', '15A'), ('15B', '15B'), ('15C', '15C'), ('15D', '15D'), ('15E', '15E'), ('15F', '15F')], max_length=10)),
                ('semana_inicio', models.DateField()),
                ('semana_fim', models.DateField()),
                ('limpeza', models.CharField(choices=[('\xd3timo', '\xd3timo'), ('Bom', 'Bom'), ('Ruim', 'Ruim'), ('Muito ruim', 'Muito ruim')], max_length=20)),
                ('lixo', models.CharField(choices=[('\xd3timo', '\xd3timo'), ('Bom', 'Bom'), ('Ruim', 'Ruim'), ('Muito ruim', 'Muito ruim')], max_length=20)),
                ('verificado', models.DateTimeField()),
                ('detalhes', models.TextField(blank=True, help_text='Anota\xe7\xf5es extras: sugest\xf5es, avisos, etc', max_length=1000, null=True)),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Limpeza',
                'verbose_name_plural': 'Limpezas',
            },
        ),
        migrations.CreateModel(
            name='Prontuario',
            fields=[
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Pessoas.Aluno')),
            ],
            options={
                'ordering': ['aluno__nome'],
                'verbose_name': 'Prontu\xe1rio',
                'verbose_name_plural': 'Prontu\xe1rios',
            },
        ),
        migrations.CreateModel(
            name='Prontuario_detalhe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.TextField(max_length=10000, verbose_name='Ocorr\xeancia')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('prontuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pd', to='Atividades.Prontuario')),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Atendimento ambulatorial',
                'verbose_name_plural': 'Atendimentos ambulatoriais',
            },
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Palavras-chave para resumir o evento.', max_length=150)),
                ('denunciante', models.CharField(blank=True, help_text='Aluno ou Servidor', max_length=100, null=True)),
                ('artigo', models.CharField(choices=[('Ato de indisciplina de baixa gravidade', (('Art.18-I', 'Art.18, I Faltar com asseio pessoal e organiza\xe7\xe3o\n                dos seus pertences e dos recursos e/ou equipamentos do IFC sob sua\n                responsabilidade ou uso.'), ('Art.18-II', 'Art.18, II\n                Descumprir o hor\xe1rio geral das atividades do campus.'), ('Art.18-III', 'Art.18, III\n                Proferir palavras obscenas ou ofensivas.'), ('Art.18-IV', 'Art.18, IV Fazer gestos obscenos.'), ('Art.18-V', 'Art.18, V N\xe3o cumprir as escalas de atividades\n                pedag\xf3gicas curriculares optativas.'), ('Art.18-VI', 'Art.18, VI Descumprir as normas do campus que\n                orientam o uso de instala\xe7\xf5es e servi\xe7os'), ('Art.18-VII', 'Art.18, VII Manter-se em\n                atitude de desinteresse ou com vistas \xe0 desordem das atividaes pedag\xf3gicas.'), ('Art.18-VIII', 'Art.18, VIII Incumbir outra pessoa do desempenho\n                de tarefa que seja de sua responsabilidade.'), ('Art.18-IX', 'Art.18, IX Apresentar-se sem uniforme nas atividades\n                pedag\xf3gicas, caso as normas estabelecidas pelo campus instituam a necessidade\n                de seu uso.'), ('Art.18-X', 'Art.18, X Entrar nas depend\xeancias do IFC sem autoriza\xe7\xe3o\n                ou identifica\xe7\xe3o, caso as normas estabelecidas pelo campus instituam essa\n                necessidade.'), ('Art.18-XI', 'Art.18, XI Ter outros comportamentos, n\xe3o constantes\n                nesse rol, que podem ser equiparados, pelo CAE/CGAE do campus ou pela\n                coordena\xe7\xe3o de curso, aos atos aqui arrolados.(REVOGADO)'))), ('Ato de indisciplina de m\xe9dia gravidade', (('Art.19-I', 'Art.19, I Ausentar-se da sala de aula ou das depend\xeancias do IFC\n                sem autoriza\xe7\xe3o, caso as normas estabelecidas pelo campus instituam essa\n                necessidade.'), ('Art.19-II', 'Art.19, II Omitir-se, sem justificativa, de programa\xe7\xf5es\n                esportivas, c\xedvicas, art\xedsticas e culturais, e viagens acad\xeamicas\n                quando estiver representando o campus dentro ou fora do IFC.'), ('Art.19-III', 'Art.19, III Descumprir as tarefas pedag\xf3gicas,\n                sem justificativas previstas em lei.'), ('Art.19-IV', 'Art.19, IV Usar de meios il\xedcitos durante\n                realiza\xe7\xe3o de atividades avaliativas.'), ('Art.19-V', 'Art.19, V Usar\n                de desonestidade para eximir-se das atividades pedag\xf3gicas.'), ('Art.19-VI', 'Art.19, VI Omitir\n                ou distorcer informa\xe7\xf5es quando solicitadas.'), ('Art.19-VII', 'Art.19, VII Utilizar o telefone celular ou outro equipamento\n                eletr\xf4nico que interfira no bom andamento das atividades pedag\xf3gicas, salvo\n                os casos [...] autorizados [...].'), ('Art.19-VIII', 'Art.19, VIII Efetuar transa\xe7\xe3o comercial, inclusive\n                rifas e sorteios, dentro do campus, sem a devida autoriza\xe7\xe3o.'), ('Art.19-IX', 'Art.19, IX Apresentar comportamentos ou vestimentas\n                que atentem ao pudor.'), ('Art.19-X', 'Art.19, X Fazer uso indevido de recursos tecnol\xf3gicos\n                (redes sociais, mensagens instant\xe2neas, sites em geral, e-mail, entr outros),\n                de forma a infringir o presente Regulamento.'), ('Art.19-XI', 'Art.19, XI Negligenciar o cuidado com  os animais sob sua\n                responsabilidade.'), ('Art.19-XII', 'Art.19, XII Adentrar e permanecer, em sala de aula\n                e/ou outros locais fechados, nas depend\xeancias do IFC, com animais[...].'), ('Art.19-XIII', 'Art.19, XIII Adentrar e permanecer nos locais\n                de atividades pedag\xf3gicas com pessoas n\xe3o-matriculadas, sem autoriza\xe7\xe3o\n                pr\xe9via do(a) docente ou coordenador(a) respons\xe1vel.'), ('Art.19-XIV', 'Art.19, XIV Ter outros comportamentos, n\xe3o constantes\n                nesse rol, que podem ser equiparados, pelo CAE/CGAE do campus ou pela\n                coordena\xe7\xe3o de curso, aos atos aqui arrolados.(REVOGADO)'))), ('Ato de indisciplina de alta gravidade', (('Art.20-I', 'Art.20, I Usar barragens, rios, lagos e a\xe7udes, do campus\n                e proximidades, para banho, pesca ou outras atividades afins sem autoriza\xe7\xe3o.'), ('Art.20-II', 'Art.20, II Recusar-se a seguir as normas de seguran\xe7a do trabalho\n                nas aulas de laborat\xf3rio, e/ou de campo, e visitas t\xe9cnicas.'), ('Art.20-III', 'Art.20, III Organizar e/ou praticar trote em discentes\n                sem a autoriza\xe7\xe3o da Coordena\xe7\xe3o do curso.'), ('Art.20-IV', 'Art.20, IV Portar ou depositar bebida alco\xf3lica, cigarros ou\n                outras drogras l\xedcitas, nas depend\xeancias do IFC, se maior de idade.'), ('Art.20-V', 'Art.20, V Ter outros comportamentos, n\xe3o constantes\n                nesse rol, que podem ser equiparados, pelo CAE/CGAE do campus ou pela\n                coordena\xe7\xe3o de curso, aos atos aqui arrolados.(REVOGADO)'))), ('Infra\xe7\xf5es', (('Art.21-I', 'Art.21, I Coagir outra pessoa a qualquer atitude\n                 contr\xe1ria a sua vontade.'), ('Art.21-II', 'Art.21, II Coagir membro da comunidade do IFC\n                ou qualquer visitante \xe0 pr\xe1tica de atos atentat\xf3rios \xe0 Lei.'), ('Art.21-III', 'Art.21, III Furtar, ou sua tentativa.'), ('Art.21-IV', 'Art.21, IV Roubar, ou sua tentativa.'), ('Art.21-V', 'Art.21, V Portar ou usar qualquer esp\xe9cie de arma.'), ('Art.21-VI', 'Art.21, VI Tentar agredir ou agredir f\xedsica e/ou\n                 moralmente qualquer pessoa, nas dep\xeancias do IFC ou em \xe2mbito\n                 externo, quando em atividades pedag\xf3gicas ou em representa\xe7\xe3o\n                 do IFC.'), ('Art.21-VII', 'Art.21, VII Expor, intencionalmente ou n\xe3o,\n                a perigo a vida ou sa\xfade de outrem.'), ('Art.21-VIII', 'Art.21, VIII Praticar atos libidinosos ou obscenos.'), ('Art.21-IX', 'Art.21, IX Amea\xe7ar algu\xe9m oralmente, por escrito,\n                por meio de gestos ou qualquer outro meio simb\xf3lico.'), ('Art.21-X', 'Art.21, X Deixar de prestar assist\xeancia \xe0 pessoa\n                amea\xe7ada, constrangida ou exposta a iminente perigo, ou, quando\n                n\xe3o for poss\xedvel faz\xea-lo sem risco \xe0 pr\xf3pria integridade f\xedsica, n\xe3o\n                solicitar o socorro devido.'), ('Art.21-XI', 'Art.21, XI Usar de maneira indevida os diferentes espa\xe7os\n                do campus, colocando em risco a integridade pr\xf3pria e/ou de\n                terceiros.'), ('Art.21-XII', 'Art.21, XII Praticar atos atentat\xf3rios\n                \xe0 dignidade [...].'), ('Art.21-XIII', 'Art.21, XIII Aplicar trotes atentat\xf3rios\n                \xe0 dignidade ou que coloquem em risco \xe0 vida de outrem.'), ('Art.21-XIV', 'Art.21, XIV Praticar, induzir ou incitar,\n                por qualquer meio, a discrimina\xe7\xe3o ou o preconceito [...].'), ('Art.21-XV', 'Art.21, XV Praticar toda e qualquer a\xe7\xe3o de\n                intimida\xe7\xe3o, agress\xf5es intencionais, verbais ou f\xedsicas feitas\n                de maneira repetitiva, que configure a pr\xe1tica de bullying.'), ('Art.21-XVI', 'Art.21, XVI Praticar viol\xeancia ou abuso\n                contra animais, ou qualquer outra forma de viola\xe7\xe3o das leis vigentes.'), ('Art.21-XVII', 'Art.21, XVII Portar ou depositar bebida alco\xf3lica,\n                cigarros ou outras drogas l\xedcitas, nas depend\xeancias do IFC, se menor de idade.'), ('Art.21-XVIII', 'Art.21, XVIII Portar ou depositar drogas\n                il\xedcitas nas depend\xeancias do IFC.'), ('Art.21-XIX', 'Art.21, XIX Usar ou incentivar o uso de\n                drogas l\xedcitas e il\xedcitas, ou apresentar sintomas de seu\n                uso, nas depend\xeancias do IFC ou externamente, em atividades\n                executadas pelo IFC, de que o (a) discente fa\xe7a parte.'), ('Art.21-XX', 'Art.21, XX Comercializar, fornecer, servir,\n                 ministrar ou entregar bebida alco\xf3lica, cigarro ou outras\n                 drogas l\xedcitas e il\xedcitas, dentro do IFC, em atividade\n                 pedag\xf3gica ou atividade em que estiver representando o IFC.'), ('Art.21-XXI', 'Art.21, XXI Adulterar ou falsificar pareceres\n                ou documentos.'), ('Art.21-XXII', 'Art.21, XXII Recorrer a meios fraudulentos para lograr\n                vantagem para si ou para outrem.'), ('Art.21-XXIII', 'Art.21, XXIII Utilizar pessoal ou recursos\n                materiais do IFC em servi\xe7os ou atividades particulares.'), ('Art.21-XXIV', 'Art.21, XXIV Depredar o patrim\xf4nio p\xfablico\n                ou privado.'), ('Art.21-XXV', 'Art.21, XXV Promover ou participar de atos de\n                vandalismo.'), ('Art.21-XXVI', 'Art.21, XXVI Praticar a retirada de equipamentos,\n                produtos e outros itens que constituem patrim\xf4nio do IFC,\n                sem a pr\xe9via autoriza\xe7\xe3o de seus respons\xe1veis.'), ('Art.21-XXVII', 'Art.21, XXVII Cometer pl\xe1gio, ou seja,\n                apropriar-se, parcialmente ou na \xedntegra, do trabalho de outrem\n                e utiliz\xe1-lo como se fosse seu, sem lhe dar o devido cr\xe9dito,\n                ou seja, sem cit\xe1-lo como fonte.'), ('Art.21-XXVIII', 'Art.21, XXVIII Usar de forma indevida o\n                nome ou o s\xedmbolo do IFC, sendo agravante o uso a fim de\n                tirar proveito, para si ou para outrem, ou a fim de difamar a institui\xe7\xe3o.'), ('Art.21-XXIX', 'Art.21, XXIX Promover eventos usando o\n                nome do IFC sem a devida autoriza\xe7\xe3o da Dire\xe7\xe3o.'), ('Art.21-XXX', 'Art.21, XXX  Divulgar, ceder ou comercializar\n                dados relativos a pesquisas do IFC, sem a autoriza\xe7\xe3o de\n                autoridade competente.'), ('Art.21-XXXI', 'Art.21, XXXI Devassar o conte\xfado ou se\n                apossar indevidamente de correspond\xeancia alheia.'), ('Art.21-XXXII', 'Art.21, XXXII Acessar computadores, softwares,\n                dados, informa\xe7\xf5es, redes ou por\xe7\xf5es restritas do sistema\n                computacional do IFC, sem a devida autoriza\xe7\xe3o.'), ('Art.21-XXXIII', 'Art.21, XXXIII Enviar spams, mensagens\n                fraudulentas, pornogr\xe1ficas ou amea\xe7adoras.'), ('Art.21-XXXIV', 'Art.21, XXXIV Outros, n\xe3o constantes\n                neste rol, que se caracterizem como infra\xe7\xf5es.(REVOGADO)')))], max_length=300)),
                ('medida_prevista', models.CharField(choices=[('Advert\xeancia escrita', 'Advert\xeancia escrita (baixa ou m\xe9dia gravidade)'), ('Realiza\xe7\xe3o de atividades pedag\xf3gicas espec\xedficas', 'Realiza\xe7\xe3o de atividades pedag\xf3gicas espec\xedficas\n        (baixa, m\xe9dia, alta gravidade ou infra\xe7\xf5es)'), ('Repara\xe7\xe3o do dano causado ao patrim\xf4nio        p\xfablico ou particular', 'Repara\xe7\xe3o do dano causado ao patrim\xf4nio\n        p\xfablico ou particular (Alta gravidade ou infra\xe7\xf5es)'), ('Retrata\xe7\xe3o verbal ou escrita', 'Retrata\xe7\xe3o verbal ou escrita (baixa, m\xe9dia, alta gravidade ou infra\xe7\xf5es)'), ('Suspens\xe3o da frequ\xeancia \xe0s atividades curriculares', 'Suspens\xe3o da frequ\xeancia \xe0s atividades curriculares\n        obrigat\xf3rias e/ou optativas, acompanhada da realiza\xe7\xe3o de atividades\n         pedag\xf3gicas espec\xedficas (Alta gravidade ou infra\xe7\xf5es)'), ('Mudan\xe7a de turno ou turma', 'Mudan\xe7a de turno ou turma (Alta gravidade ou infra\xe7\xf5es)'), ('Transfer\xeancia compuls\xf3ria, se discente do ensino m\xe9dio', 'Transfer\xeancia\n        compuls\xf3ria, se discente do ensino m\xe9dio (Infra\xe7\xf5es)'), ('Desligamento ou n\xe3o-renova\xe7\xe3o da matr\xedcula, se\n        discente de ensino superior', 'Desligamento ou n\xe3o-renova\xe7\xe3o da matr\xedcula, se\n        discente de ensino superior (Infra\xe7\xf5es)')], max_length=250)),
                ('texto', models.TextField(help_text='Os fatos ocorridos.', max_length=100000)),
                ('data', models.DateField()),
                ('denuncia', models.BooleanField(default=False, verbose_name='Escrito den\xfancia')),
                ('comunicado_discente', models.BooleanField(default=False, verbose_name='Comunicado ao discente')),
                ('encaminhado_conciliacao', models.BooleanField(default=False, verbose_name='Encaminhado para concilia\xe7\xe3o')),
                ('protocolado', models.BooleanField(default=False, verbose_name='Protocolado')),
                ('medida_aplicada', models.BooleanField(default=False)),
                ('tipo_medida', models.CharField(blank=True, choices=[('Advert\xeancia escrita', 'Advert\xeancia escrita (baixa ou m\xe9dia gravidade)'), ('Realiza\xe7\xe3o de atividades pedag\xf3gicas espec\xedficas', 'Realiza\xe7\xe3o de atividades pedag\xf3gicas espec\xedficas\n        (baixa, m\xe9dia, alta gravidade ou infra\xe7\xf5es)'), ('Repara\xe7\xe3o do dano causado ao patrim\xf4nio        p\xfablico ou particular', 'Repara\xe7\xe3o do dano causado ao patrim\xf4nio\n        p\xfablico ou particular (Alta gravidade ou infra\xe7\xf5es)'), ('Retrata\xe7\xe3o verbal ou escrita', 'Retrata\xe7\xe3o verbal ou escrita (baixa, m\xe9dia, alta gravidade ou infra\xe7\xf5es)'), ('Suspens\xe3o da frequ\xeancia \xe0s atividades curriculares', 'Suspens\xe3o da frequ\xeancia \xe0s atividades curriculares\n        obrigat\xf3rias e/ou optativas, acompanhada da realiza\xe7\xe3o de atividades\n         pedag\xf3gicas espec\xedficas (Alta gravidade ou infra\xe7\xf5es)'), ('Mudan\xe7a de turno ou turma', 'Mudan\xe7a de turno ou turma (Alta gravidade ou infra\xe7\xf5es)'), ('Transfer\xeancia compuls\xf3ria, se discente do ensino m\xe9dio', 'Transfer\xeancia\n        compuls\xf3ria, se discente do ensino m\xe9dio (Infra\xe7\xf5es)'), ('Desligamento ou n\xe3o-renova\xe7\xe3o da matr\xedcula, se\n        discente de ensino superior', 'Desligamento ou n\xe3o-renova\xe7\xe3o da matr\xedcula, se\n        discente de ensino superior (Infra\xe7\xf5es)')], max_length=250, null=True, verbose_name='Tipo de medida')),
                ('controle', models.BooleanField(default=False, editable=False)),
                ('denunciado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pessoas.Aluno')),
                ('servidor', models.ForeignKey(help_text='Servidor que est\xe1 elaborando a den\xfancia.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['data'],
                'verbose_name': 'Relat\xf3rio',
                'verbose_name_plural': 'Relat\xf3rios',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(blank=True, choices=[('Geral', 'Geral'), ('1_superior', '1_superior'), ('1_inferior', '1_inferior'), ('2_superior', '2_superior'), ('2_inferior', '2_inferior'), ('3_superior', '3_superior'), ('3_inferior', '3_inferior'), ('4_superior', '4_superior'), ('4_inferior', '4_inferior'), ('5_superior', '5_superior'), ('5_inferior', '5_inferior'), ('6_superior', '6_superior'), ('6_inferior', '6_inferior'), ('7_superior', '7_superior'), ('7_inferior', '7_inferior'), ('8_superior', '8_superior'), ('8_inferior', '8_inferior'), ('9_superior', '9_superior'), ('9_inferior', '9_inferior'), ('10_superior', '10_superior'), ('10_inferior', '10_inferior'), ('11_superior', '11_superior'), ('11_inferior', '11_inferior'), ('12_superior', '12_superior'), ('12_inferior', '12_inferior'), ('13_superior', '13_superior'), ('13_inferior', '13_inferior'), ('14_superior', '14_superior'), ('14_inferior', '14_inferior'), ('15_superior', '15_superior'), ('15_inferior', '15_inferior')], max_length=15, null=True)),
                ('atividade', models.TextField(max_length=10000)),
                ('data_inicial', models.DateTimeField()),
                ('finalizado', models.BooleanField(default=False)),
                ('data_final', models.DateTimeField(blank=True, null=True)),
                ('motivo', models.TextField(blank=True, max_length=1000, null=True)),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Servi\xe7o',
                'verbose_name_plural': 'Servi\xe7os',
            },
        ),
        migrations.CreateModel(
            name='Vistoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarto', models.CharField(choices=[('1A', '1A'), ('1B', '1B'), ('1C', '1C'), ('1D', '1D'), ('1E', '1E'), ('1F', '1F'), ('2A', '2A'), ('2B', '2B'), ('2C', '2C'), ('2D', '2D'), ('2E', '2E'), ('1F', '2F'), ('3A', '3A'), ('3B', '3B'), ('3C', '3C'), ('3D', '3D'), ('3E', '3E'), ('3F', '3F'), ('4A', '4A'), ('4B', '4B'), ('4C', '4C'), ('4D', '4D'), ('4E', '4E'), ('4F', '4F'), ('5A', '5A'), ('5B', '5B'), ('5C', '5C'), ('5D', '5D'), ('5E', '5E'), ('5F', '5F'), ('6A', '6A'), ('6B', '6B'), ('6C', '6C'), ('6D', '6D'), ('6E', '6E'), ('6F', '6F'), ('7A', '7A'), ('7B', '7B'), ('7C', '7C'), ('7D', '7D'), ('7E', '7E'), ('1F', '7F'), ('8A', '8A'), ('8B', '8B'), ('8C', '8C'), ('8D', '8D'), ('8E', '8E'), ('8F', '8F'), ('9A', '9A'), ('9B', '9B'), ('9C', '9C'), ('9D', '9D'), ('9E', '9E'), ('9F', '9F'), ('10A', '10A'), ('10B', '10B'), ('10C', '10C'), ('10D', '10D'), ('10E', '10E'), ('10F', '10F'), ('11A', '11A'), ('11B', '11B'), ('11C', '11C'), ('11D', '11D'), ('11E', '11E'), ('11F', '11F'), ('12A', '12A'), ('12B', '12B'), ('12C', '12C'), ('12D', '12D'), ('12E', '12E'), ('12F', '12F'), ('13A', '13A'), ('13B', '13B'), ('13C', '13C'), ('13D', '13D'), ('13E', '13E'), ('13F', '13F'), ('14A', '14A'), ('14B', '14B'), ('14C', '14C'), ('14D', '14D'), ('14E', '14E'), ('14F', '14F'), ('15A', '15A'), ('15B', '15B'), ('15C', '15C'), ('15D', '15D'), ('15E', '15E'), ('15F', '15F')], max_length=5)),
                ('portas', models.CharField(choices=[('Muito ruim', 'Muito ruim'), ('Ruim', 'Ruim'), ('Regular', 'Regular'), ('Bom', 'Bom'), ('\xd3timo', '\xd3timo')], max_length=20)),
                ('armarios', models.CharField(choices=[('Muito ruim', 'Muito ruim'), ('Ruim', 'Ruim'), ('Regular', 'Regular'), ('Bom', 'Bom'), ('\xd3timo', '\xd3timo')], max_length=20, verbose_name='Arm\xe1rios')),
                ('vidros', models.CharField(choices=[('Muito ruim', 'Muito ruim'), ('Ruim', 'Ruim'), ('Regular', 'Regular'), ('Bom', 'Bom'), ('\xd3timo', '\xd3timo')], max_length=20)),
                ('beliches', models.CharField(choices=[('Muito ruim', 'Muito ruim'), ('Ruim', 'Ruim'), ('Regular', 'Regular'), ('Bom', 'Bom'), ('\xd3timo', '\xd3timo')], max_length=20)),
                ('mesa', models.CharField(choices=[('Muito ruim', 'Muito ruim'), ('Ruim', 'Ruim'), ('Regular', 'Regular'), ('Bom', 'Bom'), ('\xd3timo', '\xd3timo')], max_length=20)),
                ('detalhes', models.TextField()),
                ('motivo', models.CharField(choices=[('Pedido de troca', 'Pedido de troca'), ('Interesse da administra\xe7\xe3o', 'Interesse da administra\xe7\xe3o')], max_length=30)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-data'],
                'verbose_name': 'Vistoria',
                'verbose_name_plural': 'Vistorias',
            },
        ),
        migrations.AddField(
            model_name='comunicados',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Pessoas.Aluno'),
        ),
        migrations.AddField(
            model_name='comunicados',
            name='servidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
