# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 16:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Atividades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatorio',
            name='avaliado',
        ),
    ]
