# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 00:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Atividades', '0002_remove_relatorio_avaliado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educacional',
            options={'ordering': ['aluno__nome'], 'verbose_name': 'Atendimento educacional', 'verbose_name_plural': 'Atendimentos educacionais'},
        ),
    ]
